### ISSUE TITLE
the latest build of Zenith Gold is black screen window

### ISSUE THREAD

**Issue by burinss** [gitbetter/Zenith#6] opened 2021-02-03 17:55 UTC

**Comment by gitbetter** [comment] 2021-02-03 23:29
Sorry to hear about that but thanks for creating an issue for this.

I need more information in order to understand how you got to the black screen.

* What build flags did you build the engine with when running the builder script? (`build.sh` or `build.ps1`)
* Is the entire screen black or only the viewport window (if you built the engine with the editor. i.e. without the `-headless` flag)?
* Have you tried running the build multiple times? Is it always a black screen no matter what? There is a known issue where the demo scene won't always get a `ZSceneReadyEvent` due to the asynchronous nature of the asset loading. I am still looking into this one.
* Do you see any colored output in the console window? (yellow or red for warnings and errors, respectively)
* What is your environment? Are you on a Mac or a PC? And what OS are you using? I have only tested the most recent changes to the engine on a PC so Mac is still up in the air for the moment.

Please provide some or all of this info so I can look further into the issue and push a fix ASAP.

Thanks again for reporting it.

**Comment by burinss** [comment] 2021-02-04 02:23
I used build.ps1 to build with editor. Entire screen is black, but it uses gpu. Only debug configuration is possible to build, another ones have so much compile errors. Zenith master build is working but it reports "shader compile error" in console. Im using pc(win10)

**Comment by gitbetter** [comment] 2021-02-04 02:33
Ok thank you. I am actively developing on the Gold branch so it is not completely stable yet, but I will update this issue once it is.
master is a bit behind so I will merge Gold into it once it is stable enough.
Shouldn't be too long now.

If you are building using build.ps1, make sure to pass in the `-development` flag to it, otherwise it will look for a packaged `Asset.zip` to use for the engine assets. `-development` will ensure it uses the unpackaged Assets directory.

**Comment by gitbetter** [comment] 2021-02-18 09:13
Blackout issues are no longer reproducible on Windows 10 so I'll be closing this issue. The above description seems to have been a result of building without the `-development` flag (which would require that the engine assets be in a .zip.

**Closed** 2021-02-18 09:14 UTC
Labels: bug
